config/routes.rb
Rails.application.routes.draw do
  get 'uploader/index'

  get 'uploader/form'
  post 'uploader/form' => 'uploader#form'
  post 'uploader/upload'
  get 'uploader/download'
  get 'music/uploader/search' => 'uploader#search'
  get 'music/search/' => 'music#search'
  post 'music/new' => 'music#create'
  patch '/music/:music_id/uploader/:id' => 'uploader#update'

  devise_for :users
  resources :users, only: :show
  root 'main#index'
  resources :main
    # get 'main' => 'main#index'
  resources :music do
    resources :uploader do
      resources :comments, only: [:index, :new, :create]
    end
  end

end
  # get   'music/new'  =>  'music#new'

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :upload_file
end

app/models/music.rb
class Music < ActiveRecord::Base

  has_many :upload_files
end

app/models/upload_file.rb
class UploadFile < ActiveRecord::Base
  mount_uploader :file, UploadFileUploader
  belongs_to :music
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :upload_files

         has_attached_file :avatar,
                      styles:  { medium: "300x300#", thumb: "100x100#" }
  validates_attachment_content_type :avatar,
                                      content_type: ["image/jpg","image/jpeg","image/png"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_out_path_for(resource)
      '/' # サインアウト後のリダイレクト先URL
    end

    def after_sign_up_path_for(resource)
      '/'
    end

def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: :new

 def index
  @comments = Comment.where(uploader_id: params[:uploader_id])
  @upload_file = UploadFile.find(params[:uploader_id])
 end

  def new
    @upload_file = UploadFile.find(params[:upload_file.id])
    @comment = Comment.new
  end

  def create
    @comment = Comment.create(create_params)
    redirect_to controller: :comments, action: :index
  end


 private
  def create_params
   params.require(:comment).permit(:nickname, :rate, :comments).merge(uploader_id: params[:uploader_id])
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index

  end
end

app/controllers/music_controller.rb
class MusicController < ApplicationController
    skip_before_filter :verify_authenticity_token

  def index
    @musics = Music.all

    # @musics = Music.find_by(uid: "")

  end

  def create

# @music = Music.where(uid: music_params)
  # unless @music
    @music = Music.create(music_params)

    redirect_to "/music/#{@music.id}"

  end

  def new
    @music = Music.new
    @songtitle = params[:title]
  end

  def show

  @music = Music.find(params[:id])
  @upload_file = UploadFile.where(music_id: params[:id])

      # @uploader = UploadFile.find(params[:uploader_id])
  end

  def search
    if Music.where(songtitle: params[:songtitle]).any?
     @music = Music.where(songtitle: params[:songtitle]).limit(20)
   else
     @music =Music.new
     redirect_to new_music_path(@music, title: params[:songtitle])
   end

  end

  private
  def music_params
    params.require(:music).permit(:uid, :songtitle, :id)
  end
  def uploader_params
    params.permit(:music_id)
  end

  def destroy
    @upload_file = UploadFile.find(params[:id])
    if upload_file.user_id == current_user.id
      upload_file.destroy
    end
    redirect_to music_path(@music)
  end

end

app/controllers/uploader_controller.rb
class UploaderController < ApplicationController
  def index
    @upload_file = UploadFile.where('songtitle LIKE(?)', "%#{params[:songtitle]}%")
    # binding.pry

  end

  def form
    # binding.pry
  end

  def show
    @uploader = UploadFile.find(params[:uploader_id])
    @user = User.find(id: @upload_file.user_id)
  end



  def search
    @upload_file = UploadFile.where(songtitle: params[:keyword]).limit(20)


  end

  def destroy
    @upload_file = UploadFile.find(params[:id])
    if @upload_file.user_id == current_user.id
      @upload_file.destroy
    end
    @music_id = params[:music_id]
    redirect_to user_path(current_user.id)
  end

  def upload
# binding.pry

      # songtitle = "%#{params[:songtitle]}%"
      @upload_file = current_user.upload_files.new( params.require(:upload_file).permit(:title, :file, :songtitle, :music_id, :user_id) )
      # @upload_file = UploadFile.new( params.require(:upload_file).permit(:title, :file, :songtitle) )
      @upload_file.save
      @music = Music.find(@upload_file.music_id)

      redirect_to music_path(@music)
  end

  def edit
      @upload_file = UploadFile.find(params[:id])
    end

def update
      @upload_file = UploadFile.find(params[:id])

        @upload_file.update(upload_file_params)
        @music = Music.find(@upload_file.music_id)
        redirect_to user_path(current_user.id)
    end
# params.require(:upload_file).merge(user_id: current_user.id)

  # def download
  #   @upload_file = UploadFile.find(params[:id].to_i)
  #   filepath = @upload_file.file.current_path
  #   stat = File::stat(filepath)
  #   send_file(filepath, :filename => @upload_file.file.url.gsub(/.*\//,''), :length => stat.size)
  # end
private

def upload_file_params
  params.permit(:title, :file, :songtitle, :music_id)
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  @upload_file = current_user.upload_files.page(params[:page]).per(5).order("created_at DESC")
  @music_id = params[:music_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/music_helper.rb
module MusicHelper
end

app/helpers/uploader_helper.rb
module UploaderHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<title>Pitchsound コメント</title>
<div class="row">
    <%= link_to "投稿一覧へ戻る", :back %>
</div>
<div class="comments-title">
  <p class="username">Title：<%= @upload_file.title %></p>
  <div class="play">
    <a class="playbutton" onClick="sound()">再生する</a>
  </div>
  <audio  id="sound-file" controls src= <%= @upload_file.file %>>
  </audio>
</div>
<div class="comments-content clearfix">
  <p class="comments">コメント</p>
  <HR color="#191970">
  <ul class="list-comments">
    <% @comments.reverse_order.each do |comment| %>
    <li class="commentlist" style="border-bottom: dotted 1px">
      <h2>ニックネーム：
      <span><i class="text-xxsmall" title=""></i></span><%= comment.nickname %>
      </h2>
      <h2>評価
        <span class="rating-star"><i class="star-actived rate-<%= comment.rate %>0"></i></span>
      </h2>
      <h2>コメント：</h2>
      <p>
        <%= comment.comments %>
      </p>
    </li>
    <% end %>
  </ul>
</div>
<footer>
  <div class="tab_contents clearfix">
    <div class="tab1-1" name="tab1">
     <%= link_to 'Search', "/music", method: :get , class: "tabmenu"%>
    </div>
    <div class="tab2-1" name="tab2">
      <% if user_signed_in? %>
        <%= link_to 'Mypage', user_path(current_user), method: :get , class: "tabmenu"%>
      <% else %>
        <%= link_to 'Login', "/users/sign_in", method: :get , class: "tabmenu"%>
      <% end %>
    </div>
  </div>
</footer>
</body>
</html>

<footer>
<div class="uploadcontents">
<% @comment = Comment.new %>
  <h2 class="whitefont">
    コメントする

  <%= form_for @comment, url: music_uploader_comments_path, method: :post do |f| %>
    <%= f.hidden_field :uploader_id, :value => @upload_file.id %>
    <%= f.text_field :nickname, :class => "nicknamefield", placeholder: 'ニックネーム' %>
    <br>
    <%= f.label :評価 %>
    <%= f.number_field :rate, placeholder: '評価', value: 1, max: 10, min: 1, :class =>"ratefield" %>
    <br>
    <%= f.text_field :comments, :class => "commentsfield", placeholder: 'コメントを入力' %><br>
    <%= f.submit "Upload", :class => "uploadbutton" %>
    </h2>
<% end %>
</div>
</footer>

app/views/comments/new.html.erb
<title>Pitchsound 投稿フォーム</title>

<div class="uploadcontents">
    <h3>
      投稿する
    </h3>

<%= form_for [@upload_file, @comment] do |f| %>
          <div style="margin: 8px 0">
            <%= f.label :nickname, style: { 'margin-right' => 8 } %>
            <%= f.text_field :nickname, placeholder: 'nickname', value: '' %>
          </div>
          <div style="margin: 8px 0">
            <%= f.label :評価, style: { 'margin-right' => 8 } %>
            <%= f.number_field :rate, placeholder: '評価', value: 1, max: 10, min: 1, html: { class: "search__query", style: 'text-align: right;' } %>
          </div>
          <div style="margin: 8px 0">
            <%= f.text_area :comments, placeholder: 'コメントを書いてね！', style: 'width: 100%;height: 300px;' %>
          </div>
          <div class="row">
            <div class="col10 push1">
              <%= button_tag type: "submit", class: "btn btn--block" do %>
              投稿する<i class="icon-arrow-right"></i>
              <% end %>
            </div>
          </div>
          <% end %>

<!--     <input placeholder="Username" type="text" name="name" autofocus><br>
    <textarea cols="60" name="text" placeholder="text" rows="20"></textarea>
    <div class="upload">
 
    <input type="file" class="upload_form">
  </div>
  <input type="image" src="uploadphoto.png" value="SENT" width=10%>
</div> -->
 <div class="contents row">
    <div class="success">
      <a class="btn" href="/tweets">投稿一覧へ戻る</a>
    </div>
  </div>

<footer>

    <div class="tab_contents clearfix">
            <div class="tab1-1" name="tab1">
             <%= link_to 'Search', "/music", method: :get , class: "tabmenu"%>
           </div>
            <div class="tab2-1" name="tab2">
            <% if user_signed_in? %>
              <%= link_to 'Mypage', user_path(current_user), method: :get , class: "tabmenu"%>
            <% else %>
            <%= link_to 'Login', "/users/sign_in", method: :get , class: "tabmenu"%>
          <% end %>

            </div>
    </div>

</footer>

app/views/layouts/application.html.erb
<html>
  <head>
    <meta charset="UTF-8" />
<!--     <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=0.6667, user-scalable=0;">
    <link rel="stylesheet" href="style.css"> -->
    <title>Pitchsound</title>
     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://www.youtube.com/iframe_api"></script>
  </head>
  <body>
    <header>
       <div class="heading clearfix">
        <h1><%= link_to 'Pitchsound', "/", method: :get , class: "title" %></h1>
        <% if user_signed_in? %>
          <div class="entry_button" style="right: 50%">
            <%= link_to 'Sign Out', "/users/sign_out", method: :delete %>
          </div>
        <% end %>


      </div>
    </header>


  </body>

<%= yield %>

</body>
  </html>

app/views/main/index.html.erb
    <div class="top-content">
      <ul>
      <div style="position: relative;">
          <div style="list-style: none;">
          <%= image_tag 'top_1.jpg', :width => "100%" %>

          </div>
        <h3 class="pr-sentence1">Pitchsoundは、音楽好きのための音源投稿プラットフォーム</h3>
      </div>
      </ul>
    </div>
    <div class="middle-content">
       <ul>
       <div style="position: relative;">
          <div style="list-style: none;">
            <%= image_tag 'IMG_4145.jpg', :width => "100%" %>
          </div>
       <h3 class="pr-sentence2">好きな曲をピアノでカバーしてみたり、友達とカラオケで歌ってみたり...そんな思い出は誰かと共有したいもの</h3>
      </div>
      </ul>
    </div>

    <div class="bottom-content">
       <ul>
       <div style="position: relative;">
          <div style="list-style: none;">
            <%= image_tag 'IMG_4148.jpg', :width => "100%" %>
          </div>
        <h3 class="pr-sentence3">さあ、あなたのデバイスで眠っているその音楽を、Pitchsoundでシェアしてみませんか。</h3>
        </div>
      </ul>
    </div>

<footer>

    <div class="tab_contents clearfix">
            <div class="tab1-2" name="tab1">
            <%= link_to 'Search', "/music", method: :get , class: "tabmenu"%>


            </div>
            <div class="tab2-1" name="tab2">
            <% if user_signed_in? %>
              <%= link_to 'Mypage', user_path(current_user), method: :get , class: "tabmenu"%>
            <% else %>
            <%= link_to 'Login', "/users/sign_in", method: :get , class: "tabmenu"%>
          <% end %>
              <!-- <a href="#tab2" class="tabmenu">Mypage</a> -->
              <!-- <%= link_to 'ログイン', "/users/sign_in", method: :get , class: "tabmenu"%> -->
              <!-- <%= link_to 'ログアウト', "/users/sign_out", method: :delete , class: "tabmenu"%> -->
            </div>
    </div>

</footer>

app/views/music/index.html.erb
<div class="searchbox">
  <p class="searchsentence">アレンジをお探しの方は</p>
  <%= form_tag('/music/uploader/search', method: :get) do %>
    <div class="searchcenter">
      <input class="search__query" name="keyword" placeholder="曲名で検索" type="text" value=""><button class="btn-search" songtitle="検索" type="submit">検索</button></input>
    </div>
  <% end %>
</div>


<div class="uploadbox">
  <p class="searchsentence2">自分のアレンジを<br>投稿したい方は</p>
  <div class="searchcenter">
    <% if user_signed_in? %>
      <%= form_tag('/music/search', method: :get) do %>
        <input class="search__query" name="songtitle" placeholder="投稿したい曲を検索" type="text" value=""><button class="btn-search2" songtitle="検索" type="submit">検索</button></input>
      <% end %>
      <% else %>
        <%= link_to 'Login！', "/users/sign_in", method: :get , class: "tabmenu"%>
      <% end %>
  </div>
</div>

<div class="blank">
<div class="new">☆What's new☆</div>
<ul class="list-music">
<% UploadFile.all.reverse_order.each do |upload_file| %>
  <ul class="list-menu">
    <div class="right-content">
      <li class="border">
        <p class="username">曲名：<%= upload_file.songtitle %><br>
        タイトル:
          <%= upload_file.title %><br>
        </p>
        <h2>(Userid:<%= upload_file.user_id %>)<br></h2>
        <% @music = Music.where(id: upload_file.music_id) %>

        <%= link_to 'コメント一覧', music_uploader_comments_path(@music[0], upload_file.id), method: :get , class: "upload-yours clearfix", id: "post_a"%>
        <ul>
      <div class="play">
        <a class="playbutton" onClick="sound()">再生する</a>
      </div>
          <audio id="sound-file" controls src= <%= upload_file.file %> class="audiosize">
          </audio>
        </ul>
      </li>
    </div>
  </ul>
<% end %>
</ul>
</div>



<footer>
  <div class="tab_contents clearfix">
    <div class="tab1-1" name="tab1">
     <%= link_to 'Search', "/music", method: :get , class: "tabmenu"%>
   </div>
    <div class="tab2-1" name="tab2">
      <% if user_signed_in? %>
        <%= link_to 'Mypage', user_path(current_user), method: :get , class: "tabmenu"%>
      <% else %>
        <%= link_to 'Login', "/users/sign_in", method: :get , class: "tabmenu"%>
  <% end %>
    </div>
  </div>
</footer>

app/views/music/music.html.erb
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=0.6667, user-scalable=0;"> 
    <link rel="stylesheet" href="style.css">
    <title>Pitchsound 検索結果</title>
  </head>
  <body>
  <% if user_signed_in? %>
                <li class="entry_button" style="right: 30%">
                  <%= link_to 'Sign Out', "/users/sign_out", method: :delete %>
                </li>

              <% end %>

 <div class=”video”>

    <iframe width="560" height="315" src="https://www.youtube.com/embed/5BodIFoW55c" frameborder="0" allowfullscreen></iframe>
    "ハナミズキ"の検索結果

</div>

    <input type="submit" value="新規投稿", class="upload-yours clearfix">


<ul class="list-menu">
  <div class="left-content">
    <li><a href="#"><p class="username">Username</p></a><a href="#">投稿１</a></li>
  </div>

  <div class="right-content">
    <li><input type="image" src= "playbutton.png" width="70%" alt="" class="relative button"/></li>
  </div>

<div class="left-content">
    <li><a href="#"><p class="username">Username</p></a><a href="#">投稿2</a></li>
  </div>

  <div class="right-content">
  <li><input type="image" src= "playbutton.png" width="70%" alt="" class="relative button"/></li>
  </div>



<div class="left-content">
    <li><a href="#"><p class="username">Username</p></a><a href="#">投稿3</a></li>
  </div>

  <div class="right-content">
  <li><input type="image" src= "playbutton.png" width="70%" alt="" class="relative button"/></li>
  </div>

</ul>
<footer>

    <div class="tab_contents clearfix">
            <div class="tab1-1" name="tab1"><a href="#tab1" class="tabmenu">Search</a></div>
            <div class="tab2-1" name="tab2"><a href="#tab2" class="tabmenu">Mypage</a></div>
    </div>

</footer>

  </body>
</html>

app/views/music/new.html.erb
<h3 class="newfont">
      Congratulations!<br>You are the first to upload this song!<br>

</h3>
<h3 class="newfont2">
  <form id="search" onsubmit="return false;">
    <input type="text" class="textbox" value=<%= @songtitle%> id="q" size="40" name="songtitle">
    <button type="submit" value="この曲の動画を検索" class="btn"><span>検索</span></button>
  </form>
<%= form_for @music, :url => {:action => 'create'} do |f| %>
  <%= f.hidden_field :songtitle, value: @songtitle %>
  <%= f.label :uid, "以下の検索結果から選択" %>
  <%= f.text_field :uid, :class => "urlfield", :placeholder => "またはYoutubeの動画IDをここに貼り付ける" %><br><br>
  <%= f.submit "この曲のアレンジを投稿する", :class => "registervideo" %>
<ul class="list-videos">
  <div class="insert_youtube">
  </div>
</ul>
<% end %>
</h3>


<footer>

     <div class="tab_contents clearfix">
            <div class="tab1-1" name="tab1">
             <%= link_to 'Search', "/music", method: :get , class: "tabmenu"%>
           </div>
            <div class="tab2-1" name="tab2">
            <% if user_signed_in? %>
              <%= link_to 'Mypage', user_path(current_user), method: :get , class: "tabmenu"%>
            <% else %>
            <%= link_to 'Login', "/users/sign_in", method: :get , class: "tabmenu"%>
          <% end %>

            </div>
    </div>

</footer>

app/views/music/show.html.erb
<ul class="list-menu">
  <div class="right-content">
    <ul>
      <div class="videoresult"><br>
        <p class="titlesearch">曲名：<%= @music.songtitle %></p>
        <iframe width="534" height="300" src="https://www.youtube.com/embed/<%= @music.uid %>" frameborder="0" allowfullscreen></iframe>
      </div>
    </ul>
  </div>
</ul>
<ul class="list-comments">
<% @upload_file.reverse_order.each do |upload_file| %>
  <ul class="list-menu">
  <div class="right-content">
    <li>
    <p class="username">userid:<%= upload_file.user_id %><br>
Title:
      <%= upload_file.title %><br>
    <%= link_to 'コメント一覧', music_uploader_comments_path(@music, upload_file.id), method: :get , class: "upload-yours clearfix", id: "post_a"%>
  </p>
    <ul>
  <div class="play">
    <a class="playbutton" onClick="sound()">再生する</a>
  </div>
      <audio  id="sound-file" controls src= <%= upload_file.file %>>
      </audio>
    </ul>
    </li>
  </div>
  </ul>
<% end %>
</ul>

<footer>
<div class="uploadcontents2">
<% @upload = UploadFile.new %>
  <h3 class="uploadfont">
      投稿する
    <%= form_for @upload, url: uploader_upload_path do |f| %>
      <%= f.hidden_field :songtitle, :value => @music.songtitle %>
      <%= f.hidden_field :music_id, :value => @music.id %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.text_field :title, placeholder: 'タイトル', :class => "titlefield" %><br>
      <%= f.file_field :file, :class => "filefield" %><br>
      <%= f.submit "Upload", :class => "uploadbutton" %>
    <% end %>
  </h3>
</footer>


  <footer>
     <div class="tab_contents clearfix">
            <div class="tab1-1" name="tab1">
             <%= link_to 'Search', "/music", method: :get , class: "tabmenu"%>
           </div>
            <div class="tab2-1" name="tab2">
            <% if user_signed_in? %>
              <%= link_to 'Mypage', user_path(current_user), method: :get , class: "tabmenu"%>
            <% else %>
            <%= link_to 'Login', "/users/sign_in", method: :get , class: "tabmenu"%>
          <% end %>

            </div>
    </div>

</footer>

app/views/uploader/download.html.erb
<h1>Uploader#download</h1>
<p>Find me in app/views/uploader/download.html.erb</p>

app/views/uploader/form.html.erb
    <title>Pitchsound 投稿フォーム</title>

<div class="uploadcontents">
<% @upload = UploadFile.new %>
    <h3>
      投稿する
    </h3>
    <%= form_for @upload, url: uploader_upload_path do |f| %>
      <%= f.label :songtitle, "曲名" %>
      <%= f.text_field :songtitle %>
      <%= f.label :title, "title" %>
      <%= f.text_field :title %>

      <%= f.label :file %>
      <%= f.file_field :file %>
      <%= f.submit "Upload" %>

    <% end %>

<!--
    <div class="upload"> -->
<!--
    <input type="file" class="upload_form">
  </div> -->

    <%= image_tag 'uploadphoto.png', :width => "10%" %>

</div>
<!--  <div class="contents row">
    <div class="success">
      <a class="btn" href="/tweets">投稿一覧へ戻る</a>
    </div>
  </div> -->

<footer>

    <div class="tab_contents clearfix">
            <div class="tab1-2" name="tab1">
            <%= link_to 'Songs', "/music", method: :get , class: "tabmenu"%>


            </div>
            <div class="tab2-1" name="tab2">
            <% if user_signed_in? %>
            <%= link_to 'Mypage', user_path(current_user), method: :get , class: "tabmenu"%>
            <% else %>
            <%= link_to 'Login', "/users/sign_in", method: :get , class: "tabmenu"%>
          <% end %>

            </div>
    </div>

</footer>


  </body>
</html>

app/views/uploader/search.html.erb
<div class="searchbox">
  <%= form_tag('/music/uploader/search', method: :get) do %>
    <div class="searchcenter">
      <input class="search__query" name="keyword" placeholder="曲名で検索" type="text" value=""><button class="btn-search" songtitle="検索" type="submit">検索</button></input>
    </div>
  <% end %>
</div>

<div class="blank">
  <h2 class="new">検索結果</h2>
<div class="list-music">
  <% @upload_file.reverse_order.each.with_index do |upload_file, num| %>
    <ul class="list-menu">
      <div class="right-content">
        <li>
          <p class="username">Userid:<%= upload_file.user_id %>
          <br>Title:
          <%= upload_file.title %><br>
          </p>
          <% @music = Music.where(id: upload_file.music_id) %>
          <%= link_to 'コメント一覧', music_uploader_comments_path(@music[0], upload_file.id), method: :get , class: "upload-yours clearfix", id: "post_a"%>
        <ul>
  <div class="play">
    <a class="playbutton" onClick="sound()">再生する</a>
  </div>
          <audio id="sound-file" controls src= <%= upload_file.file %>>
          </audio>
        </ul>
        </li>
      </div>
    </ul>
  <% end %>
</div>
</div>
<footer>
  <div class="tab_contents clearfix">
    <div class="tab1-1" name="tab1">
     <%= link_to 'Search', "/music", method: :get , class: "tabmenu"%>
   </div>
  <div class="tab2-1" name="tab2">
  <% if user_signed_in? %>
    <%= link_to 'Mypage', user_path(current_user), method: :get , class: "tabmenu"%>
  <% else %>
    <%= link_to 'Login', "/users/sign_in", method: :get , class: "tabmenu"%>
  <% end %>

    </div>
  </div>
</footer>

app/views/uploader/upload.html.erb
<h1>Uploader#upload</h1>
<p>Find me in app/views/uploader/upload.html.erb</p>

app/views/users/show.html.erb
<title>Pitchsound マイページ</title>

<body>


    <div class="userprofile">
      <div class="user">
      <p class="username"><%= current_user.username %><span>さんのマイページ</span></p></div>
      <div class="picture"><%= image_tag  current_user.avatar, :width => "500px", :height => "500px" %></div>
    </div>

  <div class="userupload">
        <h2><%=  current_user.username %> <span>さんのアレンジ一覧</span></h2>
  </div>


<div class="blank">
  <ul class="mypage-list">
  <div class="list-music">
  <% @upload_file.each do |upload_file| %>
    <ul class="list-menu">
      <div class="right-content">
        <li>
            <p class="username"><%= upload_file.songtitle %>のアレンジ
          <br>
            <%= upload_file.title %>
            </p>
            <%= link_to 'コメント一覧', music_uploader_comments_path(upload_file.music_id, upload_file.id), method: :get , class: "upload-yours clearfix", id: "post_a"%>
          <ul>
            <div class="play">
              <a class="playbutton" onClick="sound()">再生する</a>
            </div>
            <audio id="sound-file" controls src= <%= upload_file.file %>>
            </audio>
          </ul>
    <% if user_signed_in? && current_user.id == upload_file.user_id %>
      <h1><%= link_to '編集', edit_music_uploader_path(upload_file.music_id,upload_file.id), method: :get %>
      <%= link_to '削除', music_uploader_path(upload_file.music_id,upload_file.id), method: :delete %></h1>
    <% end %>
        </li>
      </div>
    </ul>
  <% end %>
  </div>
  </ul>
</div>
  <footer>
    <div class="tab_contents clearfix">
            <div class="tab1-2" name="tab1">            <%= link_to 'Search', "/music", method: :get , class: "tabmenu"%>
            </div>
            <div class="tab2-2" name="tab2">
            <% if user_signed_in? %>
              <%= link_to 'Mypage', user_path(current_user), method: :get , class: "tabmenu"%>
            <% else %>
            <%= link_to 'Login', "/users/sign_in", method: :get , class: "tabmenu"%>
          <% end %>
              <!-- <a href="#tab2" class="tabmenu">Mypage</a> -->
              <!-- <%= link_to 'ログイン', "/users/sign_in", method: :get , class: "tabmenu"%> -->
              <!-- <%= link_to 'ログアウト', "/users/sign_out", method: :delete , class: "tabmenu"%> -->
            </div>
    </div>
</footer>

</body>


</html>